parser: babel-eslint
env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - react
rules:
  semi:
    - error
    - never
  quotes:
    - error
    - single